project:
  type: book
  output-dir: docs
  
book:
  title: "PySchool"
  favicon: "images/pc.png"
  chapters:
    - index.qmd
    - part: Talleres
      chapters:
        - talleres/taller_1.qmd
        - talleres/taller_2.qmd
        - talleres/taller_3.qmd
    - part: Anexos
      chapters:
        - anexos/seguir_aprendiendo.qmd
        - anexos/tecnologia.qmd
        - anexos/autoria_y_colaborar.qmd
    - part: Refactor-me
      chapters:
        - prefacio/intro_progra.qmd
        - prefacio/intro_python.qmd

index:
  qmd:
lang: es

format:
  html:
    theme: spacelab
    number-sections: false
    toc: false
    page-layout: full

filters: 
  - pyodide

sin-enumeracion: true  # Esta línea es opcional para indicar que no se desea enumeración
